config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
    @categories = ["chinese", "italian", "japanese", "french", "belgian"]
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :category, :address, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    @review.save
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Index of restaurants</h1>
<ul>
<% @restaurants.each do |restaurant| %>
<li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
<% end %>
</ul>
<br/><br/>
<%= link_to "Add a new restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Add a restaurant</h1>
<%= form_for(@restaurant) do |f| %>
<%= f.label :name %>
<%= f.text_field :name, :value => @restaurant.name %>
<br/>
<%= f.label :address %>
<%= f.text_field :address, :value => @restaurant.address %>
<br/>
<%= f.label :phone_number %>
<%= f.text_field :phone_number, :value => @restaurant.phone_number %>
<br/>
<%= f.label :category %>
<%= f.select :category, options_for_select(@categories), :value => @restaurant.category %>
<br/>
<%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h2><%= @restaurant.category %></h2>
<h3><%= @restaurant.address %></h3>
<h3><%= @restaurant.phone_number %></h3>
<br/><br/>
<%= link_to "Review this restaurant", new_restaurant_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>Review <%= @restaurant.name %></h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
<%= f.label "What did you think?" %>
<%= f.input :content %>
<%= f.submit "Add review", class: "btn btn-primary" %>
<% end %>